### ISSUE TITLE
Print throws exceptions

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2-c126#9]
with following configurations Print plugin throws exceptions:

- A3
Landscape + Legend New Page -> Print Exception1
Portrait + Legend New Page -> Print Exception1
		
- A4
Portrait + Legend -> Print Exception2
Landscape + Legend New Page -> Print Exception1
Portrait + Legend New Page -> Print Exception1

Print Exception1
	
```
	Error while generating PDF:
DocumentException: ExceptionConverter: java.io.IOException: The document has no pages.
	at com.lowagie.text.pdf.PdfPages.writePageTree(Unknown Source)
	at com.lowagie.text.pdf.PdfWriter.close(Unknown Source)
	at com.lowagie.text.pdf.PdfDocument.close(Unknown Source)
	at com.lowagie.text.Document.close(Unknown Source)
	at org.mapfish.print.config.layout.LegendsBlock$Renderer.cleanup(LegendsBlock.java:710)
	at org.mapfish.print.config.layout.LegendsBlock$Renderer.render(LegendsBlock.java:291)
	at org.mapfish.print.config.layout.LegendsBlock.render(LegendsBlock.java:128)
	at org.mapfish.print.PDFUtils.createCell(PDFUtils.java:631)
	at org.mapfish.print.PDFUtils.buildTable(PDFUtils.java:616)
	at org.mapfish.print.config.layout.ColumnsBlock$1.render(ColumnsBlock.java:58)
	at org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:183)
	at org.mapfish.print.config.layout.ColumnsBlock.render(ColumnsBlock.java:56)
	at org.mapfish.print.config.layout.Page.render(Page.java:80)
	at org.mapfish.print.config.layout.Layout.render(Layout.java:74)
	at org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:30)
	at org.mapfish.print.output.PdfOutputFactory.print(PdfOutputFactory.java:62)
	at org.mapfish.print.MapPrinter.print(MapPrinter.java:184)
	at org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:409)
	at org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:190)
	at org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2555)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2544)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
	
	
Print Exception2

```
Error while generating PDF:
org.mapfish.print.InvalidValueException: url has an invalid value: ${configDir}/print_header.png
	at org.mapfish.print.config.layout.ImageBlock.render(ImageBlock.java:87)
	at org.mapfish.print.PDFUtils.createCell(PDFUtils.java:631)
	at org.mapfish.print.PDFUtils.buildTable(PDFUtils.java:616)
	at org.mapfish.print.config.layout.ColumnsBlock$1.render(ColumnsBlock.java:58)
	at org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:183)
	at org.mapfish.print.config.layout.ColumnsBlock.render(ColumnsBlock.java:56)
	at org.mapfish.print.config.layout.Page.render(Page.java:80)
	at org.mapfish.print.config.layout.Layout.render(Layout.java:67)
	at org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:30)
	at org.mapfish.print.output.PdfOutputFactory.print(PdfOutputFactory.java:62)
	at org.mapfish.print.MapPrinter.print(MapPrinter.java:184)
	at org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:409)
	at org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:190)
	at org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2555)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2544)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in path at index 10: E:/Program Files (x86)/MapStore2/webapps/mapstore/printing/print_header.png
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at org.mapfish.print.config.layout.ImageBlock.render(ImageBlock.java:85)
	... 35 more
```

**Comment by allyoucanmap** [comment]
connected to #2
